---

- name: Redefine some variables
  ansible.builtin.set_fact:
    ansible_python_executable: "{{ ansible_python.executable }}"

- name: Construct dict
  ansible.builtin.set_fact:
    showinfo_output: >-
      {
        {% for var in showinfo_vars + showinfo_vars_additional %}
        "{{ var }}": "{{ vars[var] }}"{% if not loop.last %},{% endif %}
        {% endfor %}
      }

- name: Show OS specifics of the host
  ansible.builtin.debug:
    msg: "{{ showinfo_output }}"
