---

- name: Show OS specifics of the host
  debug:
    msg: >
      {
        "ansible_distribution": "{{ ansible_distribution }}",
        "ansible_distribution_version": "{{ ansible_distribution_version }}",
        "ansible_distribution_release": "{{ ansible_distribution_release }}",
        "ansible_distribution_major_version": "{{ ansible_distribution_major_version }}",
        "ansible_os_family": "{{ ansible_os_family }}",
        "ansible_virtualization_type": "{{ ansible_virtualization_type }}"
      }
