---

- name: Converge
  hosts: all
  become: "yes"
  roles:
    - deitkrachten.showinfo
  tasks:
    - name: Include role 'ansible-role-showinfo'
      ansible.builtin.include_role:
        name: ansible-role-showinfo
